Re-organize and fix bugs
symless/jest-lint pull request #4
Opened 2024-08-21 10:01 UTC by aquacash5

Fixes #2 

Fixes:
- Move `TestPair` and `Mock` into new files.
- Fix matching multi-line mocks.
- Add matching `*` and default imports.
- Move Regex to single initialization instead of compiling the regex for each file.

2024-09-08 08:45 UTC, nbolton commented
@OwenMPhillips Would you mind testing this since you're in Synergy 3 land at the moment. If it works for you please approve, I'll go ahead and review the code.

2024-09-09 14:45 UTC, OwenMPhillips requested changes
Running `cargo run -- --help` gives me these errors:

```
error[E0658]: use of unstable library feature 'lazy_cell'
  --> src/main.rs:10:27
   |
10 | use std::{fs, path::Path, sync::LazyLock};
   |                           ^^^^^^^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
  --> src/main.rs:16:22
   |
16 | static IMPORT_REGEX: LazyLock<Regex> = LazyLock::new(|| {
   |                      ^^^^^^^^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
  --> src/main.rs:16:40
   |
16 | static IMPORT_REGEX: LazyLock<Regex> = LazyLock::new(|| {
   |                                        ^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
  --> src/main.rs:19:29
   |
19 | static IGNORE_IMPORT_REGEX: LazyLock<Regex> =
   |                             ^^^^^^^^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
  --> src/main.rs:20:5
   |
20 |     LazyLock::new(|| Regex::new(r"//#region not-mocked.*?//#endregion").unwrap());
   |     ^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
  --> src/main.rs:16:40
   |
16 | static IMPORT_REGEX: LazyLock<Regex> = LazyLock::new(|| {
   |                                        ^^^^^^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
  --> src/main.rs:20:5
   |
20 |     LazyLock::new(|| Regex::new(r"//#region not-mocked.*?//#endregion").unwrap());
   |     ^^^^^^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

For more information about this error, try `rustc --explain E0658`.
error: could not compile `jest_lint` (bin "jest_lint") due to 7 previous errors
```

2024-09-09 14:50 UTC, OwenMPhillips commented
> Running `cargo run -- --help` gives me these errors:
> 
> ```
> error[E0658]: use of unstable library feature 'lazy_cell'
>   --> src/main.rs:10:27
>    |
> 10 | use std::{fs, path::Path, sync::LazyLock};
>    |                           ^^^^^^^^^^^^^^
>    |
>    = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information
> 
> error[E0658]: use of unstable library feature 'lazy_cell'
>   --> src/main.rs:16:22
>    |
> 16 | static IMPORT_REGEX: LazyLock<Regex> = LazyLock::new(|| {
>    |                      ^^^^^^^^^^^^^^^
>    |
>    = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information
> 
> error[E0658]: use of unstable library feature 'lazy_cell'
>   --> src/main.rs:16:40
>    |
> 16 | static IMPORT_REGEX: LazyLock<Regex> = LazyLock::new(|| {
>    |                                        ^^^^^^^^
>    |
>    = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information
> 
> error[E0658]: use of unstable library feature 'lazy_cell'
>   --> src/main.rs:19:29
>    |
> 19 | static IGNORE_IMPORT_REGEX: LazyLock<Regex> =
>    |                             ^^^^^^^^^^^^^^^
>    |
>    = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information
> 
> error[E0658]: use of unstable library feature 'lazy_cell'
>   --> src/main.rs:20:5
>    |
> 20 |     LazyLock::new(|| Regex::new(r"//#region not-mocked.*?//#endregion").unwrap());
>    |     ^^^^^^^^
>    |
>    = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information
> 
> error[E0658]: use of unstable library feature 'lazy_cell'
>   --> src/main.rs:16:40
>    |
> 16 | static IMPORT_REGEX: LazyLock<Regex> = LazyLock::new(|| {
>    |                                        ^^^^^^^^^^^^^
>    |
>    = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information
> 
> error[E0658]: use of unstable library feature 'lazy_cell'
>   --> src/main.rs:20:5
>    |
> 20 |     LazyLock::new(|| Regex::new(r"//#region not-mocked.*?//#endregion").unwrap());
>    |     ^^^^^^^^^^^^^
>    |
>    = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information
> 
> For more information about this error, try `rustc --explain E0658`.
> error: could not compile `jest_lint` (bin "jest_lint") due to 7 previous errors
> ```

Whoopse. Needed to update Rust.

2024-09-09 14:50 UTC, OwenMPhillips commented
> Running `cargo run -- --help` gives me these errors:
> 
> ```
> error[E0658]: use of unstable library feature 'lazy_cell'
>   --> src/main.rs:10:27
>    |
> 10 | use std::{fs, path::Path, sync::LazyLock};
>    |                           ^^^^^^^^^^^^^^
>    |
>    = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information
> 
> error[E0658]: use of unstable library feature 'lazy_cell'
>   --> src/main.rs:16:22
>    |
> 16 | static IMPORT_REGEX: LazyLock<Regex> = LazyLock::new(|| {
>    |                      ^^^^^^^^^^^^^^^
>    |
>    = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information
> 
> error[E0658]: use of unstable library feature 'lazy_cell'
>   --> src/main.rs:16:40
>    |
> 16 | static IMPORT_REGEX: LazyLock<Regex> = LazyLock::new(|| {
>    |                                        ^^^^^^^^
>    |
>    = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information
> 
> error[E0658]: use of unstable library feature 'lazy_cell'
>   --> src/main.rs:19:29
>    |
> 19 | static IGNORE_IMPORT_REGEX: LazyLock<Regex> =
>    |                             ^^^^^^^^^^^^^^^
>    |
>    = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information
> 
> error[E0658]: use of unstable library feature 'lazy_cell'
>   --> src/main.rs:20:5
>    |
> 20 |     LazyLock::new(|| Regex::new(r"//#region not-mocked.*?//#endregion").unwrap());
>    |     ^^^^^^^^
>    |
>    = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information
> 
> error[E0658]: use of unstable library feature 'lazy_cell'
>   --> src/main.rs:16:40
>    |
> 16 | static IMPORT_REGEX: LazyLock<Regex> = LazyLock::new(|| {
>    |                                        ^^^^^^^^^^^^^
>    |
>    = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information
> 
> error[E0658]: use of unstable library feature 'lazy_cell'
>   --> src/main.rs:20:5
>    |
> 20 |     LazyLock::new(|| Regex::new(r"//#region not-mocked.*?//#endregion").unwrap());
>    |     ^^^^^^^^^^^^^
>    |
>    = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information
> 
> For more information about this error, try `rustc --explain E0658`.
> error: could not compile `jest_lint` (bin "jest_lint") due to 7 previous errors
> ```

Just needed to update Rust.

2024-09-09 15:10 UTC, OwenMPhillips approved these changes

2024-09-09 15:12 UTC, OwenMPhillips approved these changes

2024-09-09 16:20 UTC, nbolton approved these changes
Unfortunately, as I'm so swamped, I don't have time to wrap my head around this change completely. Only one minor comment (at risk of being bike shed) so approving.

2024-09-09 16:20 UTC, nbolton commented on src/test_pair.rs
> +fn find_all_tests_in_directory_internal(path: &Path, tests: &mut Vec<TestPair>) {
Perhaps can come up with a better name than `find_all_tests_in_directory_internal`. When I see something like this, it makes me suspect some kind of design flaw.

2024-09-09 16:21 UTC, nbolton commented
@aquacash5 Up to you if you want to merge or improve the function name.

2024-09-10 13:03 UTC, nbolton commented
@aquacash5 I edited the PR title. Would you say this is more accurate around the primary change?

2024-09-10 14:04 UTC, merged